---
abstract: 'Defend from CSRF attacks'
author:
  - 'Ilya Tokarev <sysadm@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-DeCSRF
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Mojolicious: 3.84
  perl: 5.010001
resources:
  license: http://www.opensource.org/licenses/artistic-license-2.0
version: 0.94
